### ISSUE TITLE
[ Panic Trigger 0.4-4 ]  the application is crash when i click on trigger number

### ISSUE THREAD

**Issue by XAMIR555** [tacticalDevC/PanicTrigger#21]
#### Project Information
* Repository    :  https://github.com/tacticalDevC/PanicTrigger

* Project Name  : PanicTrigger
* Publisher     :  tacticalDevC

#### Expected behavior
I expected that  the application should not be crash when i click on the trigger number option

#### Actual behavior

After configure the application when i click on the trigher number option the application is crash you can see in bug video properly

#### How to reproduce
* [Download ](https://f-droid.org/packages/at.tacticaldevc.panictrigger/)and open the application 

* click on  [ configure] 
* and then click on [ trigger number] 
* Note the Bug
* Browser/App version:   0.4-4
* Operating system:  8.0.0 

#### Recording Of The Bug
https://youtu.be/pviwzFHup_M
#### GitHub Account
https://github.com/XAMIR555

**Comment by tacticalDevC** [comment]
Hello friend!
Thank you for reaching out to me. Could you provide me the logcat output please?
You can either do that with an application (requires root privileges) or via Android Studio.

**Comment by XAMIR555** [comment]
here is logcat 

<pre><code>04-27 03:16:51.402  6017  6017 E AndroidRuntime: FATAL EXCEPTION: main
04-27 03:16:51.402  6017  6017 E AndroidRuntime: Process: com.huawei.autoinstallapkfrommcc, PID: 6017
04-27 03:16:51.402  6017  6017 E AndroidRuntime: java.lang.RuntimeException: Unable to start receiver com.huawei.autoinstallapkfrommcc.InstallAPKReceiver: java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Boolean
04-27 03:16:51.402  6017  6017 E AndroidRuntime: 	at android.app.ActivityThread.handleReceiver(ActivityThread.java:3814)
04-27 03:16:51.402  6017  6017 E AndroidRuntime: 	at android.app.ActivityThread.-wrap18(Unknown Source:0)
04-27 03:16:51.402  6017  6017 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2082)
04-27 03:16:51.402  6017  6017 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:108)
04-27 03:16:51.402  6017  6017 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:166)
04-27 03:16:51.402  6017  6017 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7529)
04-27 03:16:51.402  6017  6017 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
04-27 03:16:51.402  6017  6017 E AndroidRuntime: 	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245)
04-27 03:16:51.402  6017  6017 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921)
04-27 03:16:51.402  6017  6017 E AndroidRuntime: Caused by: java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Boolean
04-27 03:16:51.402  6017  6017 E AndroidRuntime: 	at android.app.SharedPreferencesImpl.getBoolean(SharedPreferencesImpl.java:312)
04-27 03:16:51.402  6017  6017 E AndroidRuntime: 	at com.huawei.autoinstallapkfrommcc.InstallAPKReceiver.onReceive(InstallAPKReceiver.java:42)
04-27 03:16:51.402  6017  6017 E AndroidRuntime: 	at android.app.ActivityThread.handleReceiver(ActivityThread.java:3804)
04-27 03:16:51.402  6017  6017 E AndroidRuntime: 	... 8 more
04-27 03:17:35.282  8600  8600 E AndroidRuntime: FATAL EXCEPTION: main
04-27 03:17:35.282  8600  8600 E AndroidRuntime: Process: com.huawei.autoinstallapkfrommcc, PID: 8600
04-27 03:17:35.282  8600  8600 E AndroidRuntime: java.lang.RuntimeException: Unable to start receiver com.huawei.autoinstallapkfrommcc.InstallAPKReceiver: java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Boolean
04-27 03:17:35.282  8600  8600 E AndroidRuntime: 	at android.app.ActivityThread.handleReceiver(ActivityThread.java:3814)
04-27 03:17:35.282  8600  8600 E AndroidRuntime: 	at android.app.ActivityThread.-wrap18(Unknown Source:0)
04-27 03:17:35.282  8600  8600 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2082)
04-27 03:17:35.282  8600  8600 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:108)
04-27 03:17:35.282  8600  8600 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:166)
04-27 03:17:35.282  8600  8600 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7529)
04-27 03:17:35.282  8600  8600 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
04-27 03:17:35.282  8600  8600 E AndroidRuntime: 	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245)
04-27 03:17:35.282  8600  8600 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921)
04-27 03:17:35.282  8600  8600 E AndroidRuntime: Caused by: java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Boolean
04-27 03:17:35.282  8600  8600 E AndroidRuntime: 	at android.app.SharedPreferencesImpl.getBoolean(SharedPreferencesImpl.java:312)
04-27 03:17:35.282  8600  8600 E AndroidRuntime: 	at com.huawei.autoinstallapkfrommcc.InstallAPKReceiver.onReceive(InstallAPKReceiver.java:42)
04-27 03:17:35.282  8600  8600 E AndroidRuntime: 	at android.app.ActivityThread.handleReceiver(ActivityThread.java:3804)
04-27 03:17:35.282  8600  8600 E AndroidRuntime: 	... 8 more
04-27 22:08:09.236 27239 27239 E AndroidRuntime: FATAL EXCEPTION: main
04-27 22:08:09.236 27239 27239 E AndroidRuntime: Process: at.tacticaldevc.panictrigger, PID: 27239
04-27 22:08:09.236 27239 27239 E AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{at.tacticaldevc.panictrigger/at.tacticaldevc.panictrigger.ContactPickerActivity}: java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
04-27 22:08:09.236 27239 27239 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3303)
04-27 22:08:09.236 27239 27239 E AndroidRuntime: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3411)
04-27 22:08:09.236 27239 27239 E AndroidRuntime: 	at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:5477)
04-27 22:08:09.236 27239 27239 E AndroidRuntime: 	at android.app.ActivityThread.-wrap19(Unknown Source:0)
04-27 22:08:09.236 27239 27239 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2000)
04-27 22:08:09.236 27239 27239 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:108)
04-27 22:08:09.236 27239 27239 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:166)
04-27 22:08:09.236 27239 27239 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7529)
04-27 22:08:09.236 27239 27239 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
04-27 22:08:09.236 27239 27239 E AndroidRuntime: 	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245)
04-27 22:08:09.236 27239 27239 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921)
04-27 22:08:09.236 27239 27239 E AndroidRuntime: Caused by: java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
04-27 22:08:09.236 27239 27239 E AndroidRuntime: 	at at.tacticaldevc.panictrigger.ContactPickerActivity.onCreate(ContactPickerActivity.java:90)
04-27 22:08:09.236 27239 27239 E AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:7383)
04-27 22:08:09.236 27239 27239 E AndroidRuntime: 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1218)
04-27 22:08:09.236 27239 27239 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3256)
</code></pre>

**Comment by tacticalDevC** [comment]
Thank you very much I will investigate this issue now. Please keep in mind that it could take a while until it is fixed. I don't have that much time :)

**Comment by XAMIR555** [comment]
thanks u sir

**Comment by tacticalDevC** [comment]
Hello XAMIR555,
Since you opened this issue I changed the lines shown in the stacktrace. Can you still reproduce the bug? If yes can you please provide me a new stacktrace?
